"""
07 — MCP Client Example

Shows how to build an MCP client that connects to a server, discovers capabilities,
calls tools, reads resources, gets prompts, and handles notifications.

Connects to 06_multi_capability_server.py by default.

Run: python 07_client_example.py
"""

import asyncio
import json
import sys
from pathlib import Path

from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client
import mcp.types as types


# ── Helpers ───────────────────────────────────────────────────────────────────

def separator(title: str = "") -> None:
    line = "─" * 60
    if title:
        print(f"\n{line}\n  {title}\n{line}")
    else:
        print(f"\n{line}")


def print_tool_result(result: types.CallToolResult) -> None:
    status = "ERROR" if result.isError else "OK"
    print(f"  [{status}]")
    for block in result.content:
        if hasattr(block, "text"):
            for line in block.text.splitlines():
                print(f"    {line}")
        elif hasattr(block, "data"):
            print(f"    [Image: {block.mimeType}, {len(block.data)} bytes]")


# ── Notification handler ──────────────────────────────────────────────────────

async def handle_notification(notification) -> None:
    """Handle server-sent notifications."""
    method = getattr(notification, "method", str(type(notification).__name__))
    print(f"\n  [NOTIFICATION] {method}")
    params = getattr(notification, "params", None)
    if params:
        if hasattr(params, "uri"):
            print(f"    URI: {params.uri}")
        if hasattr(params, "data"):
            print(f"    Data: {params.data}")


# ── Demo sections ─────────────────────────────────────────────────────────────

async def demo_initialization(session: ClientSession) -> None:
    separator("1. INITIALIZATION")
    result = session._initialized_result
    if result:
        print(f"  Server name:    {result.serverInfo.name}")
        print(f"  Server version: {result.serverInfo.version}")
        print(f"  Protocol:       {result.protocolVersion}")
        caps = result.capabilities
        print(f"  Tools:     {'✓' if caps.tools     else '✗'}")
        print(f"  Resources: {'✓' if caps.resources else '✗'}")
        print(f"  Prompts:   {'✓' if caps.prompts   else '✗'}")
        print(f"  Sampling:  {'✓' if caps.sampling  else '✗'}")


async def demo_tools(session: ClientSession) -> None:
    separator("2. TOOLS")

    # List tools
    result = await session.list_tools()
    print(f"  Found {len(result.tools)} tools:")
    for t in result.tools:
        print(f"    • {t.name:<20} {(t.description or '')[:60]}")

    # Call: calculate
    separator("  2a. calculate")
    print("  >> calculate('2 ** 10')")
    r = await session.call_tool("calculate", {"expression": "2 ** 10"})
    print_tool_result(r)

    print("  >> calculate('sqrt(144) + pi')")
    r = await session.call_tool("calculate", {"expression": "sqrt(144) + pi"})
    print_tool_result(r)

    print("  >> calculate('1 / 0')  [soft error demo]")
    r = await session.call_tool("calculate", {"expression": "1 / 0"})
    print_tool_result(r)

    # Call: server_status
    separator("  2b. server_status")
    print("  >> server_status()")
    r = await session.call_tool("server_status", {})
    print_tool_result(r)

    # Call: list_files
    separator("  2c. list_files")
    print("  >> list_files()")
    r = await session.call_tool("list_files", {})
    print_tool_result(r)

    # Call: write then read a file
    separator("  2d. write_file + read_file")
    test_content = "# MCP Client Test\n\nGenerated by 07_client_example.py\n"
    print("  >> write_file('mcp_test.md', ...)")
    r = await session.call_tool("write_file", {
        "path":    "mcp_test.md",
        "content": test_content,
    })
    print_tool_result(r)

    print("  >> read_file('mcp_test.md')")
    r = await session.call_tool("read_file", {"path": "mcp_test.md"})
    print_tool_result(r)


async def demo_resources(session: ClientSession) -> None:
    separator("3. RESOURCES")

    # List resources
    result = await session.list_resources()
    print(f"  Found {len(result.resources)} resources:")
    for res in result.resources[:10]:
        mime = res.mimeType or "?"
        print(f"    • {res.uri:<40} ({mime})")
    if len(result.resources) > 10:
        print(f"    ... and {len(result.resources) - 10} more")

    # Read server://status
    separator("  3a. Read server://status")
    r = await session.read_resource("server://status")
    for content in r.contents:
        if hasattr(content, "text"):
            try:
                data = json.loads(content.text)
                for k, v in data.items():
                    print(f"    {k}: {v}")
            except json.JSONDecodeError:
                print(f"    {content.text}")

    # Read server://config
    separator("  3b. Read server://config")
    r = await session.read_resource("server://config")
    for content in r.contents:
        if hasattr(content, "text"):
            try:
                data = json.loads(content.text)
                for k, v in data.items():
                    print(f"    {k}: {v}")
            except json.JSONDecodeError:
                print(f"    {content.text}")

    # Try to read a file resource (if any listed)
    file_resources = [res for res in result.resources if res.uri.startswith("file://")]
    if file_resources:
        separator("  3c. Read a file resource")
        first = file_resources[0]
        print(f"  >> read_resource('{first.uri}')")
        r = await session.read_resource(first.uri)
        for content in r.contents:
            if hasattr(content, "text"):
                lines = content.text.splitlines()
                preview = lines[:5]
                for line in preview:
                    print(f"    {line}")
                if len(lines) > 5:
                    print(f"    ... ({len(lines) - 5} more lines)")


async def demo_prompts(session: ClientSession) -> None:
    separator("4. PROMPTS")

    # List prompts
    result = await session.list_prompts()
    print(f"  Found {len(result.prompts)} prompts:")
    for p in result.prompts:
        args = [a.name for a in (p.arguments or [])]
        print(f"    • {p.name:<20} args={args}")

    # Get code_review prompt
    separator("  4a. code_review prompt")
    print("  >> get_prompt('code_review', {code: ..., language: 'python'})")
    r = await session.get_prompt(
        "code_review",
        {
            "code": (
                "def divide(a, b):\n"
                "    return a / b\n"
            ),
            "language": "python",
        },
    )
    print(f"  Description: {r.description}")
    for msg in r.messages:
        role    = msg.role
        content = msg.content
        text    = getattr(content, "text", str(content))
        preview = text[:200].replace("\n", "\\n")
        print(f"  [{role}]: {preview}{'...' if len(text) > 200 else ''}")

    # Get explain prompt
    separator("  4b. explain prompt")
    r = await session.get_prompt(
        "explain",
        {"topic": "MCP sampling primitive", "audience": "beginner"},
    )
    print(f"  Description: {r.description}")
    for msg in r.messages:
        text = getattr(msg.content, "text", "")[:200]
        print(f"  [{msg.role}]: {text}")


async def demo_pagination(session: ClientSession) -> None:
    separator("5. PAGINATION (tools)")

    all_tools = []
    cursor    = None
    page      = 0
    while True:
        if cursor:
            result = await session.list_tools(cursor=cursor)
        else:
            result = await session.list_tools()
        all_tools.extend(result.tools)
        page += 1
        if not getattr(result, "nextCursor", None):
            break
        cursor = result.nextCursor

    print(f"  Retrieved {len(all_tools)} tools across {page} page(s)")


async def demo_error_handling(session: ClientSession) -> None:
    separator("6. ERROR HANDLING")

    from mcp.shared.exceptions import McpError

    # Unknown tool → hard error
    print("  >> call_tool('nonexistent_tool', {})  [expect McpError]")
    try:
        await session.call_tool("nonexistent_tool", {})
        print("  [UNEXPECTED: no error raised]")
    except McpError as e:
        print(f"  [McpError caught] code={e.error.code} msg={e.error.message!r}")
    except Exception as e:
        print(f"  [Other error] {type(e).__name__}: {e}")

    # Path traversal → soft error
    print("\n  >> read_file('../../etc/passwd')  [expect soft error]")
    r = await session.call_tool("read_file", {"path": "../../etc/passwd"})
    print_tool_result(r)

    # Unknown resource → hard error
    print("\n  >> read_resource('unknown://xyz')  [expect McpError]")
    try:
        await session.read_resource("unknown://xyz")
        print("  [UNEXPECTED: no error raised]")
    except McpError as e:
        print(f"  [McpError caught] code={e.error.code} msg={e.error.message!r}")
    except Exception as e:
        print(f"  [Other error] {type(e).__name__}: {e}")


async def demo_ping(session: ClientSession) -> None:
    separator("7. PING / KEEP-ALIVE")
    import time
    t0 = time.perf_counter()
    await session.send_ping()
    ms = (time.perf_counter() - t0) * 1000
    print(f"  Ping round-trip: {ms:.2f}ms")


# ── Main ──────────────────────────────────────────────────────────────────────

async def main() -> None:
    server_script = Path(__file__).parent / "06_multi_capability_server.py"
    if not server_script.exists():
        print(f"Error: server script not found: {server_script}", file=sys.stderr)
        sys.exit(1)

    print("Connecting to 06_multi_capability_server.py...")

    params = StdioServerParameters(
        command=sys.executable,
        args=[str(server_script)],
        env={
            "WORKSPACE": str(Path(__file__).parent),
            "LOG_LEVEL": "ERROR",   # suppress server logs during demo
        },
    )

    async with stdio_client(params) as (read_stream, write_stream):
        async with ClientSession(read_stream, write_stream) as session:
            # Register notification handler before initialize
            session.on_notification = handle_notification

            # Initialize
            await session.initialize()
            print("Connected!\n")

            # Run all demos
            await demo_initialization(session)
            await demo_tools(session)
            await demo_resources(session)
            await demo_prompts(session)
            await demo_pagination(session)
            await demo_error_handling(session)
            await demo_ping(session)

            separator("DONE")
            print("  All demos completed successfully.")


if __name__ == "__main__":
    asyncio.run(main())
