#!/usr/bin/env python3
"""Generate cryptographic keys required by the MCP System.

Run this script once during initial setup to produce values
for MCP_SECRET_KEY, JWT_SECRET_KEY, and STORAGE_ENCRYPTION_KEY.

Usage:
    python scripts/generate_keys.py
    python scripts/generate_keys.py --output .env.generated
"""

from __future__ import annotations

import argparse
import secrets
import sys
from pathlib import Path


def generate_urlsafe(n: int = 32) -> str:
    return secrets.token_urlsafe(n)


def generate_fernet_key() -> str:
    try:
        from cryptography.fernet import Fernet
        return Fernet.generate_key().decode()
    except ImportError:
        print("Warning: cryptography not installed, skipping Fernet key generation", file=sys.stderr)
        return "<install cryptography package to generate>"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate MCP System cryptographic keys")
    parser.add_argument(
        "--output", "-o",
        type=str,
        default=None,
        help="Write output to file instead of stdout",
    )
    args = parser.parse_args()

    mcp_secret = generate_urlsafe(32)
    jwt_secret = generate_urlsafe(32)
    fernet_key = generate_fernet_key()

    output_lines = [
        "# Generated by scripts/generate_keys.py",
        "# Copy these into your .env file.",
        "# NEVER commit .env to version control.",
        "",
        f"MCP_SECRET_KEY={mcp_secret}",
        f"JWT_SECRET_KEY={jwt_secret}",
        f"STORAGE_ENCRYPTION_KEY={fernet_key}",
        "",
    ]

    output = "\n".join(output_lines)

    if args.output:
        Path(args.output).write_text(output)
        print(f"Keys written to {args.output}")
    else:
        print(output)


if __name__ == "__main__":
    main()
